(ツ)_/¯ Edit: 06-03-2025 08:58:06 PM

diff --git a/NIXOS/SCRIPTS/BASHRC/local-bashrc b/NIXOS/SCRIPTS/BASHRC/local-bashrc
--- a/NIXOS/SCRIPTS/BASHRC/local-bashrc
+++ b/NIXOS/SCRIPTS/BASHRC/local-bashrc
@@ -1,27 +1,36 @@
 # ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
-# |                                         konsole related                                                                           | 
+# |                                         konsole related                                                                           |
 # └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
 PS1="\[\e[1;m\]┌(\[\e[1;32m\]\u\[\e[1;34m\]@\h\[\e[1;m\]) \[\e[1;m\]➤\[\e[1;36m\] \W \[\e[1;m\] \n\[\e[1;m\]└\[\e[1;33m\]➤\[\e[0;m\]  "
 
 # ┌───────────────────────────────────────────────────────────────────────────────────────────────┐
 # |                                          Nvidia session                                       |
 # └───────────────────────────────────────────────────────────────────────────────────────────────┘
+# export __GL_THREADED_OPTIMIZATION=1
+# export __GLX_VENDOR_LIBRARY_NAME=nvidia
+
 export LIBVA_DRIVER_NAME=nvidia
+export MOZ_ENABLE_WAYLAND=1                    # Enables Wayland support for Firefox
+export NIXOS_OZONE_WL=1
+export QT_LOGGING_RULES="*=false"
 export WLR_NO_HARDWARE_CURSORS=1
-export __GLX_VENDOR_LIBRARY_NAME=nvidia
 export __GL_SHADER_CACHE=1
-export __GL_THREADED_OPTIMIZATION=1
+
+REPO_DIR="$HOME/MyGit/tolga-scripts"
+GIT_REMOTE_URL="git@github.com:tolgaerok/tolga-scripts.git"
 
 # ┌───────────────────────────────────────────────────────────────────────────────────────────────┐
 # |                                          ALIAS                                                |
 # └───────────────────────────────────────────────────────────────────────────────────────────────┘
+alias repo="cd $REPO_DIR || { echo 'Failed to navigate to $REPO_DIR'; exit 1; }"
 alias cl="clear"
 alias rb='cl && echo -e "\e[33mUpdating Channels\e[0m" && sudo nix-channel --update && echo -e "\e[33mRebuilding System\e[0m" && sudo nixos-rebuild switch --upgrade && echo -e "\e[33mOptimising NixStore\e[0m" && nix-store --optimise'
-# && sysctl -p
 alias io="cat /sys/block/sda/queue/scheduler"
 alias tmpC="sudo chmod 1777 /var/tmp"
 alias n="sudo chown -R $(whoami):$(id -gn) /etc/nixos && sudo chmod -R 777 /etc/nixos && sudo chmod +x /etc/nixos/* && export NIXPKGS_ALLOW_INSECURE=1"
 alias gitup="~/gitup.sh"
 
-
-cl && echo "" && fortune | lolcat && echo "" && echo ""
+# ┌───────────────────────────────────────────────────────────────────────────────────────────────┐
+# |                                          FUN                                                                 |
+# └───────────────────────────────────────────────────────────────────────────────────────────────┘
+cl && echo "" && fortune | lolcat && echo "" && echo ""  # A fun way to start with fortune!
